navItems:
  - href: '#about'
    label: 'About'
  - href: '#carreer'
    label: 'Carreer'
  - href: '#blog'
    label: 'Blog'
  - href: '#resume'
    label: 'Resume'
  - href: '#contact'
    label: 'Contact'