navItems:
  - href: '#about'
    label: 'About'
  - href: '#career'
    label: 'Career'
  - href: '#blog'
    label: 'Blog'
  - href: '#resume'
    label: 'Resume'
  - href: '#contact'
    label: 'Contact'